### PR TITLE
When DOM prepend more than option

### PR DESCRIPTION
**Pull request by sculove**
## Details
 - fix bug about issue
 - rearrange testcase

## Reference
#45

## Preferred Reviewer
@jongmoon  @taihoon-kim

### CODE REVIEW

**Comment by happyhj** [comment]
Unit.asyncTest method is deprecated and will be removed in QUnit 2.0.0.
It is better to use QUnit.test() in conjunction with assert.async() instead.

https://api.qunitjs.com/QUnit.asyncTest/

**Comment by sculove** [comment]
@happyhj  ok.
I change testcase of other components like movableCoord...
#48

**Comment by happyhj** [comment]
LGTM

**Comment by netil** [comment]
LGTM

**Comment by jongmoon** [comment]
LGTM

**Comment by sculove** [comment]
@jongmoon thank you for your LGTM

**Pull request merged**
