### PR TITLE
Cleantask#3

### PR DESCRIPTION
**Pull request by sculove**
## Details
- remove clean task
- adjust grunt-contrib-clean

## Reference
#3 

## Preferred reviewer
@happyhj  @happyhj

### CODE REVIEW

**Comment by happyhj** [comment]
LGTM

**Comment by happyhj** [comment]
LGTM

**Comment by netil** [comment]
LGTM

**Comment by happyhj** [comment]
[LGTM](http://lgtm.in/i/QuI4CSXrn)

**Comment by happyhj** [comment]
LGTM

**Comment by happyhj** [comment]
LGTM

**Pull request merged**
